### ISSUE TITLE
Error when building a document - figures

### ISSUE THREAD

**Issue by stevejpurves** [myst-templates/cageo#2]
A document with this template build but with non fatal errors.

When there are figures in the myst document, the following error occurs for each figure:

```
./paper.fff:1: LaTeX3 Error: The key 'cas/fig/!htbp' is unknown and is being ignored.
```

This template defines a custom `figure` environment, which does not seem to accept the normal option string `!htbp`.

Removing the `[!htpb]` option fixes the error

**Comment by fwkoch** [comment]
This doesn't feel good - is it common to override standard environments...?

Just thinking through this a bit:
- easiest place to handle customization is the `template.yml` - but supporting this specific issue would mean adding a specific field like `remove_figure_htpb_option` or something, gross if we need a bunch of these specific customizations
- there could be a kluge-y way to do this in the latex, like define our own `figure` environment which does take the `[!htpb]` option, but then returns their `figure` environment without the option...
- the last option I can think of is providing a custom javascript `figure` handler to `myst-to-tex` which overrides the default. But this feels like a big can of worms: defining js plugins inside myst-template repos and using them during the build... dicey.

**Comment by stevejpurves** [comment]
yes, redefining commands is common -- basically in latex it's do what you want inside the scope of that templateor document.

When we were first doing this in python a played with a couple of ideas similar to this 

(i) having a "config" where we could customise the latex produced by the myst in some tight way... this sounds closest to the first option you suggest. but instead of a single option per customization it took more of a per command view and tried to be generic i.e. 

```
config:
   figure:
       options: false
```

This also maybe ties in with something we heard on the webinar this week i..e "this template uses `tabularx` instead of `tabular` - how do we achieve that?"

so the config there might be:
```
config:
   table:
      environment: tabularx
```

but then how to create the `tabularx` environment in the right way.... sounds more like a plugin no?


on your second suggesting, yeah I guess I could do that in the template -- add the latex to wrap their figure environment, in a new one and eat the option. That seems workable as it's very template specific but it's not nice in that is increases the complexity of creating a myst template, definitely you have to be very comfortable with latex and maybe specifics of the template you are looking at to get that right. (Also IIRC there are some limitations about what you can override -- i remember problems with this approach when dealing with verbatim environments before and code highlighting.)

on your last option, maybe there is a role for plugins here but having then load from the templates doesn't sound good, I agree -- but a plugin interface is maybe a good way internally to allow extensibility to deal with these cases.

Sounds like option (ii) is the way to go for an immediate fix for this template but should we be considering (i) -- maybe keep an eye on this as we start seeing more special cases?
